package com.mocktpo.util.constants;

/**
 * View Type Constants
 */
public interface VT {

    int VIEW_TYPE_CHANGING_VOLUME = 1;
    int VIEW_TYPE_GENERAL_TEST_INFO = 2;
    int VIEW_TYPE_HEADSET = 3;
    int VIEW_TYPE_READING_DIRECTIONS = 4;
    int VIEW_TYPE_READING_FILL_TABLE_QUESTION = 5;
    int VIEW_TYPE_READING_PROSE_SUMMARY_QUESTION = 6;
    int VIEW_TYPE_READING_SECTION_END = 7;
    int VIEW_TYPE_READING_TEXT = 8;
    int VIEW_TYPE_READING_TEXT_WITH_QUESTION = 9;
    int VIEW_TYPE_LISTENING_DIRECTIONS = 10;
    int VIEW_TYPE_TEST_INTRO = 11;
}
