package com.mocktpo.util.constants;

/**
 * View Type Constants
 */
public interface VT {

    /* General View Types */

    int VIEW_TYPE_TEST_INTRO = 1;
    int VIEW_TYPE_GENERAL_TEST_INFO = 2;

    /* Reading Section View Types */

    int VIEW_TYPE_READING_SECTION_DIRECTIONS = 11;
    int VIEW_TYPE_READING_PASSAGE = 12;
    int VIEW_TYPE_READING_QUESTION = 13;
    int VIEW_TYPE_READING_INSERT_TEXT_QUESTION = 14;
    int VIEW_TYPE_READING_PROSE_SUMMARY_QUESTION = 15;
    int VIEW_TYPE_READING_CATEGORY_CHART_QUESTION = 16;
    int VIEW_TYPE_READING_SECTION_END = 17;

    /* Listening Section View Types */

    int VIEW_TYPE_HEADSET = 21;
    int VIEW_TYPE_CHANGING_VOLUME = 22;
    int VIEW_TYPE_LISTENING_SECTION_DIRECTIONS = 23;
    int VIEW_TYPE_LISTENING_MATERIAL = 24;
    int VIEW_TYPE_LISTENING_REPLAY = 25;
    int VIEW_TYPE_LISTENING_QUESTION = 26;
    int VIEW_TYPE_LISTENING_MULTIPLE_ANSWERS_QUESTION = 27;
    int VIEW_TYPE_LISTENING_ORDER_EVENTS_QUESTION = 28;
    int VIEW_TYPE_LISTENING_MATCH_OBJECTS_QUESTION = 29;
    int VIEW_TYPE_LISTENING_SECTION_END = 210;
    int VIEW_TYPE_LISTENING_DIRECTIONS = 211;

    /* Speaking Section View Types */

    int VIEW_TYPE_SPEAKING_SECTION_DIRECTIONS = 31;

    /* Writing Section View Types */

    int VIEW_TYPE_WRITING_SECTION_DIRECTIONS = 41;
}
